In [2]:
import pandas as pd
df = pd.read_csv("../datasets/pizza_delivery.csv")
df.head()

,day,date,time,operator,branch,driver,temperature,bill,pizzas,free_wine,got_wine,discount_customer
0,Thursday,01-May-14,35.128367,Laura,East,Bruno,68.287716,58.4,4,0,0,1
1,Thursday,01-May-14,25.203074,Melissa,East,Salvatore,70.997791,26.4,2,0,0,0
2,Thursday,01-May-14,45.643404,Melissa,West,Salvatore,53.394145,58.1,3,1,0,0
3,Thursday,01-May-14,29.374298,Melissa,East,Salvatore,70.306596,35.2,3,0,0,0
4,Thursday,01-May-14,29.994610,Melissa,West,Salvatore,71.501688,38.4,2,0,0,0

In [4]:
df =  df.round(1)

In [5]:
df.head()

,day,date,time,operator,branch,driver,temperature,bill,pizzas,free_wine,got_wine,discount_customer
0,Thursday,01-May-14,35.1,Laura,East,Bruno,68.3,58.4,4,0,0,1
1,Thursday,01-May-14,25.2,Melissa,East,Salvatore,71.0,26.4,2,0,0,0
2,Thursday,01-May-14,45.6,Melissa,West,Salvatore,53.4,58.1,3,1,0,0
3,Thursday,01-May-14,29.4,Melissa,East,Salvatore,70.3,35.2,3,0,0,0
4,Thursday,01-May-14,30.0,Melissa,West,Salvatore,71.5,38.4,2,0,0,0

In [16]:
driver_group = df.groupby("driver")

In [17]:
driver_group

In [21]:
driver_group.ngroups

5

In [20]:
for group in driver_group:
    print(group)

('Bruno',            day       date  time operator  branch driver  temperature  bill  \
0     Thursday  01-May-14  35.1    Laura    East  Bruno         68.3  58.4
5     Thursday  01-May-14  40.3  Melissa  Centre  Bruno         60.8  61.8
6     Thursday  01-May-14  48.7    Laura    West  Bruno         58.3  57.9
9     Thursday  01-May-14  38.0  Melissa  Centre  Bruno         60.0  44.8
10    Thursday  01-May-14  42.1  Melissa  Centre  Bruno         65.5  49.5
...        ...        ...   ...      ...     ...    ...          ...   ...
1249  Saturday  31-May-14  34.4    Laura  Centre  Bruno         61.2  50.4
1250  Saturday  31-May-14  34.2    Laura    West  Bruno         66.9  52.0
1251  Saturday  31-May-14  37.9  Melissa    West  Bruno         56.2  55.8
1260  Saturday  31-May-14  42.9  Melissa  Centre  Bruno         56.0  49.8
1265  Saturday  31-May-14  35.7  Melissa    West  Bruno         58.6  42.7

      pizzas  free_wine  got_wine  discount_customer
0          4          0         0                  1
5          4          1         1                  0
6          3          1         1                  0
9          5          0         0                  0
10         4          1         0                  0
...      ...        ...       ...                ...
1249       3          0         0                  0
1250       7          0         0                  1
1251       6          0         0                  0
1260       4          1         1                  1
1265       3          0         0                  0

[329 rows x 12 columns])
('Domenico',            day       date  time operator  branch    driver  temperature  bill  \
109   Saturday  03-May-14  33.6  Melissa    East  Domenico         72.8  28.2
126   Saturday  03-May-14  42.3    Laura    East  Domenico         76.5  23.5
127   Saturday  03-May-14  20.2  Melissa    East  Domenico         71.8  44.6
132   Saturday  03-May-14  26.5  Melissa  Centre  Domenico         68.5  29.8
139   Saturday  03-May-14  25.4  Melissa    East  Domenico         71.0  31.3
...        ...        ...   ...      ...     ...       ...          ...   ...
1245  Saturday  31-May-14  30.6    Laura    West  Domenico         66.2  58.6
1248  Saturday  31-May-14  30.6    Laura    East  Domenico         66.7  25.2
1256  Saturday  31-May-14  26.4    Laura  Centre  Domenico         66.2  45.6
1258  Saturday  31-May-14  39.2    Laura    East  Domenico         54.0  31.4
1262  Saturday  31-May-14  33.8    Laura    East  Domenico         56.3  32.0

      pizzas  free_wine  got_wine  discount_customer
109        4          0         0                  0
126        2          1         1                  0
127        2          0         0                  0
132        1          0         0                  0
139        3          0         0                  0
...      ...        ...       ...                ...
1245       2          0         0                  0
1248       1          0         0                  0
1256       2          0         0                  0
1258       3          0         0                  0
1262       1          0         0                  0

[93 rows x 12 columns])
('Luigi',            day       date  time operator  branch driver  temperature  bill  \
52      Friday  02-May-14  30.5  Melissa    West  Luigi         54.6  48.4
53      Friday  02-May-14  37.9    Laura  Centre  Luigi         59.8  41.2
55      Friday  02-May-14  34.3  Melissa    East  Luigi         71.0  37.1
56      Friday  02-May-14  29.6  Melissa    West  Luigi         68.0  46.5
60      Friday  02-May-14  37.9  Melissa    West  Luigi         61.5  41.4
...        ...        ...   ...      ...     ...    ...          ...   ...
1242  Saturday  31-May-14  35.7  Melissa    East  Luigi         69.9  32.0
1246  Saturday  31-May-14  39.6    Laura    West  Luigi         60.8  39.2
1252  Saturday  31-May-14  40.9    Laura    West  Luigi         65.6  37.2
1257  Saturday  31-May-14  34.3    Laura  Centre  Luigi         47.2  71.3
1263  Saturday  31-May-14  33.1    Laura  Centre  Luigi         58.0  45.7

      pizzas  free_wine  got_wine  discount_customer
52         3          0         0                  0
53         3          0         0                  0
55         2          0         0                  0
56         3          0         0                  0
60         3          0         0                  1
...      ...        ...       ...                ...
1242       3          0         0                  1
1246       1          0         0                  0
1252       3          1         1                  0
1257       4          0         0                  1
1263       3          0         0                  1

[142 rows x 12 columns])
('Mario',            day       date  time operator  branch driver  temperature  bill  \
7     Thursday  01-May-14  34.0  Melissa    West  Mario         68.1  35.8
8     Thursday  01-May-14  28.2    Laura  Centre  Mario         64.9  36.6
11    Thursday  01-May-14  24.8    Laura    East  Mario         62.8  49.7
12    Thursday  01-May-14  28.3  Melissa    West  Mario         69.9  41.1
16    Thursday  01-May-14  26.1  Melissa  Centre  Mario         59.7  34.9
...        ...        ...   ...      ...     ...    ...          ...   ...
1229  Saturday  31-May-14  38.1  Melissa  Centre  Mario         50.0  38.4
1230  Saturday  31-May-14  32.1  Melissa    East  Mario         67.4  46.4
1236  Saturday  31-May-14  34.9    Laura    West  Mario         70.7  31.5
1238  Saturday  31-May-14  28.1    Laura    East  Mario         69.2  45.1
1261  Saturday  31-May-14  38.6    Laura    West  Mario         63.1  46.7

      pizzas  free_wine  got_wine  discount_customer
7          2          0         0                  0
8          2          0         0                  0
11         3          0         0                  0
12         1          0         0                  0
16         3          0         0                  0
...      ...        ...       ...                ...
1229       4          0         0                  0
1230       2          0         0                  1
1236       2          0         0                  0
1238       2          0         0                  1
1261       4          0         0                  0

[358 rows x 12 columns])
('Salvatore',            day       date  time operator  branch     driver  temperature  \
1     Thursday  01-May-14  25.2  Melissa    East  Salvatore         71.0
2     Thursday  01-May-14  45.6  Melissa    West  Salvatore         53.4
3     Thursday  01-May-14  29.4  Melissa    East  Salvatore         70.3
4     Thursday  01-May-14  30.0  Melissa    West  Salvatore         71.5
13    Thursday  01-May-14  25.5  Melissa  Centre  Salvatore         74.9
...        ...        ...   ...      ...     ...        ...          ...
1253  Saturday  31-May-14  42.3    Laura  Centre  Salvatore         66.4
1254  Saturday  31-May-14  29.1    Laura    East  Salvatore         61.4
1255  Saturday  31-May-14  42.4  Melissa  Centre  Salvatore         64.8
1259  Saturday  31-May-14  36.3  Melissa    West  Salvatore         57.3
1264  Saturday  31-May-14  36.9    Laura  Centre  Salvatore         52.8

      bill  pizzas  free_wine  got_wine  discount_customer
1     26.4       2          0         0                  0
2     58.1       3          1         0                  0
3     35.2       3          0         0                  0
4     38.4       2          0         0                  0
13    42.9       1          0         0                  0
...    ...     ...        ...       ...                ...
1253  48.5       4          1         1                  0
1254  38.9       2          0         0                  0
1255  52.9       4          1         1                  1
1259  40.0       2          0         0                  0
1264  39.0       5          0         0                  1

[344 rows x 12 columns])

In [22]:
driver_group.apply(lambda dfx : dfx[["bill", "pizzas"]].sum())

              bill  pizzas
driver
Bruno      14684.7  1046.0
Domenico    3095.8   202.0
Luigi       5831.0   390.0
Mario      15364.6  1050.0
Salvatore  15152.9  1127.0

In [24]:
group_sum  = driver_group.apply(lambda dfx : dfx[["bill", "pizzas"]].sum())

In [26]:
all_sum = df[["bill","pizzas"]].sum()

In [27]:
group_sum

              bill  pizzas
driver
Bruno      14684.7  1046.0
Domenico    3095.8   202.0
Luigi       5831.0   390.0
Mario      15364.6  1050.0
Salvatore  15152.9  1127.0

In [28]:
all_sum

bill      54129.0
pizzas     3815.0
dtype: float64

In [29]:
group_sum/ all_sum

               bill    pizzas
driver
Bruno      0.271291  0.274181
Domenico   0.057193  0.052949
Luigi      0.107724  0.102228
Mario      0.283852  0.275229
Salvatore  0.279941  0.295413

In [35]:
def prop(dfx):
    return dfx[["bill",'pizzas']].sum() / df[["bill","pizzas"]].sum()
    
driver_group.apply(prop)

               bill    pizzas
driver
Bruno      0.271291  0.274181
Domenico   0.057193  0.052949
Luigi      0.107724  0.102228
Mario      0.283852  0.275229
Salvatore  0.279941  0.295413

In [40]:
def prop(dfx, cols):
    return dfx[cols].sum() / df[cols].sum()
    
driver_group.apply(lambda dfx: prop(dfx, ["time","bill","free_wine"])).round(2)

           time  bill  free_wine
driver
Bruno      0.27  0.27       0.33
Domenico   0.06  0.06       0.03
Luigi      0.11  0.11       0.07
Mario      0.28  0.28       0.27
Salvatore  0.27  0.28       0.30

In [44]:
driver_group.apply(lambda dfx : dfx['time'].mean()).round(2)

driver
Bruno        35.31
Domenico     29.32
Luigi        33.38
Mario        34.46
Salvatore    34.63
dtype: float64

In [45]:
df["bill"].mean()

42.75592417061611

In [47]:
driver_group["time"].agg('mean')

driver
Bruno        35.312158
Domenico     29.320430
Luigi        33.377465
Mario        34.458380
Salvatore    34.633430
Name: time, dtype: float64

In [54]:
def meanGroupBy(df,group, cols):
    groups = df.groupby(group)
    return groups.apply(lambda dfx : dfx[cols].mean())

In [55]:
meanGroupBy(df,"operator",'time')

operator
Laura      34.102194
Melissa    34.358121
dtype: float64

In [56]:
def meanGroupBy(df,group, cols):
    groups = df.groupby(group)
    return groups.apply(lambda dfx : dfx[cols].agg("mean"))

In [57]:
meanGroupBy(df,"driver",'bill')

driver
Bruno        44.634347
Domenico     33.288172
Luigi        41.063380
Mario        42.917877
Salvatore    44.049128
dtype: float64